name: fitween
description: fitween

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # authentication (firebase excluded)
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.1.0
  flutter_secure_storage: ^8.0.0

  # state management
  get: ^4.6.5

  # localization
  easy_localization: ^3.0.2

  # front-end
  ## image
  lottie: ^2.1.0
  flutter_svg: ^2.0.4
  flutter_gif: ^0.0.4

  ## layout
  flutter_screenutil: ^5.5.3+2

  ## widget
  pull_to_refresh: ^2.0.0
  percent_indicator: ^4.2.2
  dots_indicator: ^2.1.0
  carousel_slider: ^4.1.1
  numberpicker: ^2.1.1
  animated_flip_counter: ^0.2.4
  table_calendar: ^3.0.8
  bottom_sheet_bar: ^2.3.1
  flutter_shake_animated: ^0.0.5
  animated_text_kit: ^4.2.2
  text_scroll: ^0.2.0
  webview_flutter: ^4.2.2
  syncfusion_flutter_charts: ^23.1.40

  # back-end
  ntp: ^2.0.0
  intl: ^0.18.0
  health: ^7.0.1
  basic_utils: ^5.5.4
  pausable_timer: ^1.0.0+7
  permission_handler: ^10.0.0
  flutter_local_notifications: ^15.0.1
  connectivity: ^3.0.6
  in_app_review: ^2.0.6

  # firebase
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  firebase_messaging: ^14.5.0
  firebase_in_app_messaging: ^0.7.2
  firebase_core_platform_interface: ^4.7.0

  # tensorflow related: must not be changed
  image: ^3.1.0
  camera: ^0.9.4+5
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1



dependency_overrides:
  camera_android: 0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/badge/
    - assets/image/challenge/complete/
    - assets/image/challenge/default/
    - assets/image/challenge/focus/
    - assets/image/icon/selected/dark/
    - assets/image/icon/selected/light/
    - assets/image/icon/unselected/
    - assets/image/level/distance/
    - assets/image/level/height/
    - assets/image/level/weight/
    - assets/image/level/
    - assets/image/logo/
    - assets/image/page/challenge/
    - assets/image/page/contents/
    - assets/image/page/contents/adventure/
    - assets/image/page/contents/workout/
    - assets/image/page/home/
    - assets/image/page/home/rotation/
    - assets/image/page/onboarding/
    - assets/image/page/goal_setting/
    - assets/image/page/see_more/goal_edit/
    - assets/image/widget/dialog/
    - assets/image/widget/ranking/
    - assets/json/locale/
    - assets/json/data/
    - assets/json/data/level/
    - assets/model/lite-model_movenet_singlepose_lightning_3.tflite

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard/Pretendard-Medium.otf