// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjAk04orBUIjwjEKhEy5JGb6YXj231NWA',
    appId: '1:694967646362:web:59d9b7dd29d7fb417f4723',
    messagingSenderId: '694967646362',
    projectId: 'fitween-626d7',
    authDomain: 'fitween-626d7.firebaseapp.com',
    storageBucket: 'fitween-626d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9U4-WGw3e-O6vbZSFbiA-7Xj2ywv7Md4',
    appId: '1:694967646362:android:0c4556eb5e58e84c7f4723',
    messagingSenderId: '694967646362',
    projectId: 'fitween-626d7',
    storageBucket: 'fitween-626d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_MrQTF01FHsBQg7YLDPMs9LH7VaE3znQ',
    appId: '1:694967646362:ios:01f3ffcf0fe4e4397f4723',
    messagingSenderId: '694967646362',
    projectId: 'fitween-626d7',
    storageBucket: 'fitween-626d7.appspot.com',
    iosClientId: '694967646362-9u5dc04ma0p4oe7c0ndnni555ga4rv1r.apps.googleusercontent.com',
    iosBundleId: 'com.fitween.fitween',
  );
}
